#!/bin/bash

if [[ ! -z $1 ]]; then
	PORT=$1
else
	PORT=3000
fi

docker pull mrseccubus/github-pages:latest
if [[ $(uname -a|grep -i microsoft|wc -l) -gt 0 ]]; then
	IP=$(ip addr show eth0 |grep "inet "|awk '{ print $2 }'|sed 's/\/.*$//')
	echo "*******************************************************************************************"
	echo "On WSL2 the docker container is reachable via these urls: "
	echo "http://$IP:$PORT or http://localhost:$PORT"
	echo "*******************************************************************************************"
else
	IP=0.0.0.0
fi
if [[ "$(uname)" == "Darwin" ]]; then
	POLL="--force-polling"
fi
docker run \
	--volume="$PWD:/root/project:delegated" \
	--entrypoint /bin/sh \
	--publish $PORT:$PORT \
	-ti node:20-alpine \
	-c "
	  set -x
		cd /root/project/;
		yarn 
		echo \"Starting web server on http://$IP:$PORT\"
		while [ 1 ] ; do
			set -e
			yarn dev
			echo 'Press CTRL+C now to quit'
			sleep 1
			set +e
			echo 'Restarting...'
		done
	"